version: '3.9'

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  app:
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - database
volumes:
  data: